services:
  # Service pour PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service pour l'API Node.js
  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      
  # Service Adminer pour gérer PostgreSQL
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"


volumes:
  postgres_data: