# Utiliser une image Node.js
FROM node:18

# Créer et utiliser le répertoire de l'application
WORKDIR /usr/src/app

RUN npm install -g nodemon ts-node

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Copier le dossier `types` contenant vos types personnalisés
# Installer les dépendances
RUN npm install

# Copier tout le reste du code source
COPY . .


# Rendre le script wait-for-it.sh exécutable
COPY wait-for-it.sh .
# Rendre le script exécutable
RUN chmod +x wait-for-it.sh
# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
#CMD ["./migrate_and_start.sh"]
# Commande de démarrage par défaut
CMD ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start:dev"]