# Utiliser une image Node.js
FROM node:18

RUN apt-get update && apt-get install -y postgresql-client

# Créer et utiliser le répertoire de l'application
WORKDIR /usr/src/app

RUN npm install -g nodemon ts-node

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install --ignore-scripts

# Copier tout le reste du code source
COPY . .

# Générer Prisma
RUN npx prisma generate

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "run", "start"]