# Utiliser une image Node.js
FROM node:18

# Créer et utiliser le répertoire de l'application
WORKDIR /usr/src/app

RUN npm install -g nodemon ts-node

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY ./src/types ./src/types  
COPY ./migrate_and_start.sh ./migrate_and_start.shV
# Copier le dossier `types` contenant vos types personnalisés
# Installer les dépendances
RUN npm install

# Copier tout le reste du code source
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["./migrate_and_start.sh"]